### ISSUE TITLE
Handle movement just in one axis?

### ISSUE THREAD

**Issue by LiborZa** [bradhowes/Joystick#6]
Hi,
is it possible to enable movement for handle just in one axis? For example to just move in y-axis (up and down) like in this image:
<img width="260" alt="Screenshot 2019-03-22 at 09 33 04" src="https://user-images.githubusercontent.com/39513305/54810111-865b4300-4c85-11e9-906e-b9392605fbaf.png">
Thanks

**Comment by bradhowes** [comment]
Hi Libor. There was no way to do this with the existing API, so I added a new property called `handleConstraint` which takes a CGRect. When set it, the handle movement will be limited to the region defined by the rectangle. I updated the playground and the sample app to illustrate its use in with the "compass" joystick -- it only moves up and down now.

**Comment by LiborZa** [comment]
Hi Brad. Thank you very much for this change. One more thing. Could you update podspec so I can get latest version via CocoaPods?

**Comment by bradhowes** [comment]
Done.

**Comment by LiborZa** [comment]
Could you check it one more time? I am still getting 1.1.5 and not 2.1.1 (or 3.0.0). Thanks

**Comment by bradhowes** [comment]
My bad. I forgot to push the Podspec update to Cocoapods. In progress now.

**Comment by bradhowes** [comment]
Done.

**Comment by LiborZa** [comment]
Hi Brad, pod update now works and your changes to movement in one axis works great. Thanks

One more thing. Would it be possible to enable minimum deployment target to iOS 11.0?

**Comment by bradhowes** [comment]
I pushed a new version 2.1.2 with the deployment target set to 11.0. Let me know how it goes.
